const tabs = [
  {
    id: "1",
    name: "Home",
    subtabs: ["Home 1", "Home 2", "Home 3", "Home 4", "Home 5"],
  },
  {
    id: "2",
    name: "Shop",
    subtabs: [
      "Shop Grid - Filter",
      "Shop Grid - 3 column",
      "Shop List - Filter",
      "Shop - Filter",
      "Shop Wide",
      "Shop Single",
      "Shop Single v2",
      "Shop Wishlist",
      "Shop Cart",
      "Shop Checkout",
    ],
  },
  {
    id: "3",
    name: "Stores",
    subtabs: ["Store List", "Store Grid", "Store Single"],
  },
  {
    id: "4",
    name: "Mega menu",
    subtabs: [
      "Dairy, Bread & Eggs",
      "Butter",
      "Milk Drinks",
      "Curd & Yogurt",
      "Eggs",
      "Buns & Bakery",
      "Cheese",
      "Condensed Milk",
      "Dairy Products",

      "Breakfast & Instant Foods",
      "Breakfast Cereal",
      "Noodles, Pasta & Soup",
      "Frozen Veg Snacks",
      "Frozen Non-Veg Snacks",
      "Vermicelli",
      "Instant Mixes",
      "Batter",

      "Beverages",
      "Fruit and Juices",
      "Cold Drinks & Juices",
      "Soft Drinks",
      "Fruit Juices",
      "Coldpress",
      "Water & Ice Cubes",
      "Soda & Mixers",
      "Health Drinks",
      "Herbal Drinks",
      "Milk Drinks",
    ],
  },
  {
    id: "5",
    name: "Pages",
    subtabs: [
      "Blog",
      "Home 2",
      "Blog Single",
      "Blog Category",
      "About us",
      "404 Error",
      "Contact",
    ],
  },
  {
    id: "6",
    name: "Account",
    subtabs: ["Sign in", "Signup", "Forgot Password", "My Account"],
  },
];
export default tabs;
